AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Nodejs Stack

Parameters:
  UserPoolId:
    Type: String
    Description: ID of the Cognito User Pool

  UserPoolClientId:
    Type: String
    Description: ID of the Cognito User Pool Client

Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    Runtime: nodejs22.x
    CodeUri: .
    Architectures:
      - arm64
    Environment:
      Variables:
        NODE_OPTIONS: '--enable-source-maps'
        USER_POOL_ID: !Ref UserPoolId
        USER_POOL_CLIENT_ID: !Ref UserPoolClientId

Resources:
  ##########################################################################
  #                              Layers                                    #
  ##########################################################################
  NodejsDepsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: NodejsDepsLayer
      Description: Dependencies for the Nodejs Lambda functions
      ContentUri: ./layers/nodejs-deps
      CompatibleRuntimes:
        - nodejs22.x
    Metadata:
      BuildMethod: nodejs22.x
      BuildArchitectures:
        - arm64

  ##########################################################################
  #                              Functions                                 #
  ##########################################################################
  TokenAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TokenAuthorizerFunction
      Description: Validates JWT tokens from Cognito for API Gateway
      Handler: authorizer.authorizerHandler
      Layers:
        - !Ref NodejsDepsLayer
        - !Sub arn:aws:lambda:${AWS::Region}:094274105915:layer:AWSLambdaPowertoolsTypeScriptV2:17
      Policies:
        - AWSLambdaBasicExecutionRole
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: esnext
        Format: esm
        Sourcemap: true
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - src/lambdas/auth/authorizer.ts
        External:
          - aws-jwt-verify
          - '@aws-lambda-powertools/logger'

  SigninFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SigninFunction
      Description: Handles user signin requests
      Handler: signin.signinHandler
      Layers:
        - !Ref NodejsDepsLayer
        - !Sub arn:aws:lambda:${AWS::Region}:094274105915:layer:AWSLambdaPowertoolsTypeScriptV2:17
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:InitiateAuth
              Resource: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: esnext
        Format: esm
        Sourcemap: true
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - src/lambdas/auth/signin.ts
        External:
          - zod
          - '@aws-lambda-powertools/logger'
          - '@aws-sdk/client-cognito-identity-provider'
          - '@aws-lambda-powertools/parser'
          - '@middy/core'

Outputs:
  TokenAuthorizerFunctionArn:
    Description: ARN of the Token Authorizer Lambda Function
    Value: !GetAtt TokenAuthorizerFunction.Arn
    Export:
      Name: !Sub NodejsStack-TokenAuthorizerFunctionArn

  SigninFunctionArn:
    Description: ARN of the Signin Lambda Function
    Value: !GetAtt SigninFunction.Arn
    Export:
      Name: !Sub NodejsStack-SigninFunctionArn
