AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stateless Resources Stack

Parameters:
  AppName:
    Type: String
    Default: ServerlessHackaton

Resources:   
  NodejsBackendStackApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../../backend/nodejs/template.yaml
      Parameters:
        UserPoolId: !ImportValue "StatefulStack-UserPoolId"
        UserPoolClientId: !ImportValue "StatefulStack-UserPoolClientId"

  ApiGatewayStackApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./api-gw.yaml
    DependsOn:
      - NodejsBackendStackApp
      - PythonBackendStackApp

  PythonBackendStackApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../../backend/python/template.yaml
      Parameters:
        UserPoolId: !ImportValue "StatefulStack-UserPoolId"
        UserPoolClientId: !ImportValue "StatefulStack-UserPoolClientId"

Outputs:  
  ApiGatewayURL:
    Description: URL for the API Gateway
    Value: !GetAtt ApiGatewayStackApp.Outputs.ApiGatewayURL
    Export:
      Name: !Sub StatelessStack-ApiGatewayURL