AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Python Backend Stack (Hello World Lambda)

Parameters:
  UserPoolId:
    Type: String
    Description: ID of the Cognito User Pool

  UserPoolClientId:
    Type: String
    Description: ID of the Cognito User Pool Client

  CoordinatorAgentUrl:
    Type: String
    Description: AgentCore runtime URL for the coordinator agent
    Default: ""

  BearerToken:
    Type: String
    Description: Bearer token for coordinator agent authentication
    NoEcho: true
    Default: ""

Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    Runtime: python3.12
    CodeUri: .
    Architectures:
      - arm64

Resources:
  ##########################################################################
  #                              Functions                                 #
  ##########################################################################
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloFunction
      Description: A simple hello world function for testing
      Handler: hello.handler
      CodeUri: src/lambdas/hello/
      Policies:
        - AWSLambdaBasicExecutionRole

  CoordinatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CoordinatorFunction
      Description: Lambda function to communicate with the coordinator agent via A2A
      Handler: coordinator.handler
      CodeUri: src/lambdas/coordinator
      Timeout: 300
      Environment:
        Variables:
          COORDINATOR_AGENT_URL: !Ref CoordinatorAgentUrl
          BEARER_TOKEN: !Ref BearerToken
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  HelloFunctionArn:
    Description: ARN of the Hello Lambda Function
    Value: !GetAtt HelloFunction.Arn
    Export:
      Name: PythonStack-HelloFunctionArn

  CoordinatorFunctionArn:
    Description: ARN of the Coordinator Lambda Function
    Value: !GetAtt CoordinatorFunction.Arn
    Export:
      Name: PythonStack-CoordinatorFunctionArn
